
obj-$(CONFIG_MMI_BOOT_INFO) += mmi_boot_info.o
obj-$(CONFIG_MMI_INFO) += mmi_ram_info.o
obj-$(CONFIG_MMI_INFO) += mmi_storage_info.o
obj-$(CONFIG_MMI_INFO) += mmi_unit_info.o
obj-$(CONFIG_MMI_INFO) += mmi_info_main.o
